apiVersion: apps/v1
kind: Service
metadata:
    name: serviceapiconversao
spec:
    selector:
      app: serviceapiconversao
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
    type: NodePort